modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/DoNotDoughnut/ExampleMod/issues"
logoFile="mod_icon.png"

[[mods]]

	modId="examplemod"
	version="${file.jarVersion}"
	displayName="Example Mod"
	displayURL="https://holloway.jumpingcrab.com"
	authors="Rhys Holloway, Luke Putzeys, Kevin Justin"
	
description='''
Terraria-based items
'''

[[dependencies.examplemod]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0-beta2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

